### ISSUE TITLE
No org.aksw.sparqlify.web.Main on fresh maven install

### ISSUE THREAD

**Issue by reinvantveer** [SmartDataAnalytics/Sparqlify#62]
Using instructions from the README.md:

```
    git clone https://github.com/AKSW/Sparqlify
    cd Sparqlify
    mvn clean install
    cd sparqlify-cli
    mvn assembly:assembly
    cd ..
    sparqlify-core/bin/sparqlify
```

Error: Could not find or load main class org.aksw.sparqlify.web.Main
Building on Ubuntu server 14.04, build succes.

**Comment by Aklakan** [comment]
Should be long fixed (also mvn package supersedes assembly)
